data = '[{"ID":1001, \
            "name":"Egnatia-3isSeptembriou/Anatolika", \
            "latitude":40.626216, \
            "longitude":22.959864, \
            "Edge":[ \
                {"destination_id":1025,"weight":6}, \
                {"destination_id":1009,"weight":2}] \
        }, \
        { \
            "ID":1002, \
            "name":"Egnatia-3isSeptembriou/Boreia", \
            "latitude":40.626055, \
            "longitude":22.959845, \
            "Edge":[ \
                {"destination_id":1025,"weight":4}, \
                {"destination_id":1008,"weight":2}] \
        }, \
        { \
            "ID":1003, \
            "name":"Egnatia-3isSeptembriou/Ditika", \
            "latitude":40.626035, \
            "longitude":22.960204, \
            "Edge":[ \
                {"destination_id":1025,"weight":7}, \
                {"destination_id":1008,"weight":19}, \
                {"destination_id":1009,"weight":1}] \
        }, \
        { \
            "ID":1004, \
            "name":"Egnatia-3isSeptembriou/Notia", \
            "latitude":40.62621, \
            "longitude":22.960095, \
            "Edge":[ \
                {"destination_id":1009,"weight":5}, \
                {"destination_id":1032,"weight":3}] \
        }, \
        { \
            "ID":1005, \
            "name":"Egnatia-EthnikisAminis/Ditika", \
            "latitude":40.631093, \
            "longitude":22.953449, \
            "Edge":[ \
                {"destination_id":1029,"weight":8}] \
        }, \
        { \
            "ID":1006, \
            "name":"Egnatia-EthnikisAminis/Anatolika", \
            "latitude":40.631109, \
            "longitude":22.953224, \
            "Edge":[ \
                {"destination_id":1032,"weight":1}, \
                {"destination_id":1001,"weight":6}, \
                {"destination_id":1015,"weight":8}] \
        }, \
        { \
            "ID":1007, \
            "name":"Egnatia-EthnikisAminis/Notia", \
            "latitude":40.63114, \
            "longitude":22.95333, \
            "Edge":[ \
                {"destination_id":1015,"weight":4}, \
                {"destination_id":1001,"weight":6}, \
                {"destination_id":1019,"weight":3}] \
        }, \
        { \
            "ID":1008, \
            "name":"Egnatia-Aggelaki/Boreia", \
            "latitude":40.630870, \
            "longitude":22.953491, \
            "Edge":[ \
                {"destination_id":1029,"weight":4}, \
                {"destination_id":1019,"weight":22}, \
                {"destination_id":1015,"weight":7}] \
        }, \
        { \
            "ID":1009, \
            "name":"3isSeptembriou-Andronikou/Boreia", \
            "latitude":40.624239, \
            "longitude":22.952999, \
            "Edge":[ \
                {"destination_id":1024,"weight":7}, \
                {"destination_id":1011,"weight":4}] \
        }, \
        { \
            "ID":1011, \
            "name":"Aggelaki-Tsimiski", \
            "latitude":40.626473, \
            "longitude":22.952885, \
            "Edge":[ \
                {"destination_id":1015,"weight":3}, \
                {"destination_id":1008,"weight":12}] \
        }, \
        { \
            "ID":1013, \
            "name":"Stratou-3isSeptembriou/Anatolika", \
            "latitude":40.624956, \
            "longitude":22.954955, \
            "Edge":[ \
                {"destination_id":1009,"weight":4}] \
        }, \
        { \
            "ID":1015, \
            "name":"Tsimiski-Aminis", \
            "latitude":40.62804, \
            "longitude":22.95055, \
            "Edge":[ \
                {"destination_id":1016,"weight":3}] \
        }, \
        { \
            "ID":1016, \
            "name":"PalaiwnPatrwn-Tsimiski", \
            "latitude":40.63099, \
            "longitude":22.94577, \
            "Edge":[ \
                {"destination_id":1017,"weight":7}, \
                {"destination_id":1018,"weight":39}] \
        }, \
        { \
            "ID":1017, \
            "name":"PalaiwnPatrwn-Egnatia", \
            "latitude":40.632283, \
            "longitude":22.950832, \
            "Edge":[ \
                {"destination_id":1006,"weight":8}, \
                {"destination_id":1019,"weight":5}] \
        }, \
        { \
            "ID":1018, \
            "name":"Venizelou-Tsimiski", \
            "latitude":40.63469, \
            "longitude":22.93955, \
            "Edge":[ \
                {"destination_id":1022,"weight":5}, \
                {"destination_id":1019,"weight":4}, \
                {"destination_id":1031,"weight":3}] \
        }, \
        { \
            "ID":1019, \
            "name":"Venizelou-Egnatia/Ditika", \
            "latitude":40.63696, \
            "longitude":22.94192, \
            "Edge":[ \
                {"destination_id":1027,"weight":11}, \
                {"destination_id":1020,"weight":1}] \
        }, \
        { \
            "ID":1020, \
            "name":"Egnatia-Dwdekanisou/Notia", \
            "latitude":40.64011, \
            "longitude":22.93618, \
            "Edge":[ \
                {"destination_id":1031,"weight":6}, \
                {"destination_id":1022,"weight":1}] \
        }, \
        { \
            "ID":1022, \
            "name":"Tsimiski-Dwdekanisou", \
            "latitude":40.6364, \
            "longitude":22.93639, \
            "Edge":[ \
                {"destination_id":1023,"weight":2}] \
        }, \
        { \
            "ID":1023, \
            "name":"Politexneiou-Dikastiria", \
            "latitude":40.639168, \
            "longitude":22.931598, \
            "Edge":[] \
        }, \
        { \
            "ID":1024, \
            "name":"Andronikou-Stratou", \
            "latitude":40.626039, \
            "longitude":22.953055, \
            "Edge":[ \
                {"destination_id":1013,"weight":8}] \
        }, \
        { \
            "ID":1025, \
            "name":"3isSeptembriou-AgiouDimitriou/Boreia", \
            "latitude":40.627397, \
            "longitude":22.963468, \
            "Edge":[ \
                {"destination_id":1033,"weight":5}] \
        }, \
        { \
            "ID":1026, \
            "name":"EthnikisAminis-AgiouDimitriou/Notia", \
            "latitude":40.634332, \
            "longitude":22.956553, \
            "Edge":[ \
                {"destination_id":1007,"weight":3}] \
        }, \
        { \
            "ID":1027, \
            "name":"Egnatia-Kupriwn/Boreia", \
            "latitude":40.64006, \
            "longitude":22.93626, \
            "Edge":[ \
                {"destination_id":1028,"weight":8}] \
        }, \
        { \
            "ID":1028, \
            "name":"AgiouDimitriou-Kupriwn/Notia", \
            "latitude":40.640575, \
            "longitude":22.943244, \
            "Edge":[ \
                {"destination_id":1029,"weight":5}] \
        }, \
        { \
            "ID":1029, \
            "name":"AgiouDimitriou-EthnikisAminis/Anatolika", \
            "latitude":40.634245, \
            "longitude":22.956446, \
            "Edge":[ \
                {"destination_id":1030,"weight":5}] \
        }, \
        { \
            "ID":1030, \
            "name":"AgiouDimitriou-3isSeptembriou/Notia", \
            "latitude":40.627514, \
            "longitude":22.963414, \
            "Edge":[ \
                {"destination_id":1004,"weight":5}] \
        }, \
        { \
            "ID":1031, \
            "name":"Venizelou-Egnatia/Anatolika", \
            "latitude":40.636935, \
            "longitude":22.941939, \
            "Edge":[ \
                {"destination_id":1017,"weight":5}] \
        }, \
        { \
            "ID":1032, \
            "name":"Egnatia-Bibliothiki(Mesw Panepistimiou)", \
            "latitude":40.62945, \
            "longitude":22.95657, \
            "Edge":[ \
                {"destination_id":1033,"weight":5}, \
                {"destination_id":1005,"weight":4}] \
        }, \
        { \
            "ID":1033, \
            "name":"AgiouDitriou-Bibliothiki(Mesw Panepistimiou)", \
            "latitude":40.63233, \
            "longitude":22.96005, \
            "Edge":[ \
                {"destination_id":1026,"weight":5}] \
        }, \
        { \
            "ID":1034, \
            "name":"Ladadika-Monastoriou", \
            "latitude":40.64062, \
            "longitude":22.93506, \
            "Edge":[ \
                {"destination_id":1027,"weight":2}] \
        }]'